builds:
  - env: ["CGO_ENABLED=0"]
    goos:
      - windows
      - darwin
      - linux

    ignore:
      - goos: windows
        goarch: arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: oherych
      name: homebrew-yeelightcli
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/oherych/yeelightcli
    description: Command-line tool for managing Yeelight devices. Right now it supports 95% of all features presented in the official documentation.
    test: |
      system "#{bin}/yeelightcli"

nfpms:
  -
    id: yeelightcli
    package_name: yeelightcli
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://github.com/oherych/yeelightcli
    description: Command-line tool for managing Yeelight devices. Right now it supports 95% of all features presented in the official documentation.
    license: MIT
    formats:
      - deb
      - rpm