builds:
  - env: ["CGO_ENABLED=0"]
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
      - riscv64
    goarm:
      - 6
      - 7

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: yeelightcli
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/oherych/yeelightcli
    description: Command-line tool for managing Yeelight devices. Right now it supports 95% of all features presented in the official documentation.
    test: |
      system "#{bin}/yeelightcli"