# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yeelightcli < Formula
  desc "Command-line tool for managing Yeelight devices. Right now it supports 95% of all features presented in the official documentation."
  homepage "https://github.com/oherych/yeelightcli"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.1.3/yeelightcli_1.1.3_Darwin_x86_64.tar.gz"
      sha256 "b0a4a09983aeb8f52a13152c48ff5accf56c6ea093f7888f22dda708adbebf46"

      def install
        bin.install "yeelightcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.1.3/yeelightcli_1.1.3_Darwin_arm64.tar.gz"
      sha256 "6b3119b3c7e6b324dc8a9a3aa31f443aca4a31f995adbee6c2ae31048045e7c7"

      def install
        bin.install "yeelightcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.1.3/yeelightcli_1.1.3_Linux_x86_64.tar.gz"
      sha256 "8cf2c16dbf3b6ae2462c70773045c7ca81dea9a66b8d5afb8af739753a4a8282"

      def install
        bin.install "yeelightcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oherych/yeelightcli/releases/download/v1.1.3/yeelightcli_1.1.3_Linux_arm64.tar.gz"
      sha256 "c8063b8a0a51e500d03836b26abf25d93a60fdc16373979e0ae6a62f99a5512d"

      def install
        bin.install "yeelightcli"
      end
    end
  end

  test do
    system "#{bin}/yeelightcli"
  end
end
