name: Tests

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Try build
        run: go build main.go

      - name: Test
        run: go test -v ./...

      - name: eeen1
        run: echo $TAP_GITHUB_TOKEN | wc -c

      - name: eeen2
        env:
          DDD: ${{ secrets.TAP_GITHUB_TOKEN }}
        run: echo $DDD | wc -c

      - name: eeen3
        env:
          DDD: ${{ env.TAP_GITHUB_TOKEN }}
        run: echo $DDD | wc -c

      - name: eeen4
        env:
          DDD: ${{ TAP_GITHUB_TOKEN }}
        run: echo $DDD | wc -c

      - name: eeen5
        env:
          DDD: ${{ deploy.TAP_GITHUB_TOKEN }}
        run: echo $DDD | wc -c
