name: Tests

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Try build
        run: go build main.go

      - name: Test
        run: go test -v ./...
