name: Releaser

on:
  push:
    tags:
      - 'v**'
    branches:
      - 'build'

jobs:
  Releaser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}